"""add_bright_radius_cells_to_bv2_lights

Revision ID: 05fb7428ef76
Revises: a6197a61b7f3
Create Date: 2026-04-29 08:44:13.213011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05fb7428ef76'
down_revision: Union[str, Sequence[str], None] = 'a6197a61b7f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bv2_lights', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bright_radius_cells', sa.Float(), nullable=False, server_default='0.0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bv2_lights', schema=None) as batch_op:
        batch_op.drop_column('bright_radius_cells')

    # ### end Alembic commands ###
