"""quest_structured_rewards

Revision ID: 0885481743df
Revises: ab263c1138f6
Create Date: 2026-04-24 13:21:41.840995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0885481743df'
down_revision: Union[str, Sequence[str], None] = 'ab263c1138f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_quests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('structured_rewards', sa.Text(), nullable=True))

    with op.batch_alter_table('quest_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('structured_rewards', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quest_templates', schema=None) as batch_op:
        batch_op.drop_column('structured_rewards')

    with op.batch_alter_table('character_quests', schema=None) as batch_op:
        batch_op.drop_column('structured_rewards')

    # ### end Alembic commands ###
