"""map_builder_floors_traps

Revision ID: 225d18468679
Revises: g1h2i3j4k5l6
Create Date: 2026-04-22 11:00:26.101551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '225d18468679'
down_revision: Union[str, Sequence[str], None] = 'g1h2i3j4k5l6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('map_floors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('tile_size', sa.Integer(), nullable=False),
    sa.Column('tiles_json', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('background_color', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('map_traps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('floor_id', sa.Integer(), nullable=True),
    sa.Column('col', sa.Integer(), nullable=False),
    sa.Column('row', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('trap_type', sa.String(length=20), nullable=False),
    sa.Column('trigger_type', sa.String(length=20), nullable=False),
    sa.Column('dc_detect', sa.Integer(), nullable=False),
    sa.Column('dc_disarm', sa.Integer(), nullable=False),
    sa.Column('damage_dice', sa.Text(), nullable=False),
    sa.Column('damage_type', sa.String(length=20), nullable=False),
    sa.Column('status_effect_json', sa.Text(), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('is_triggered', sa.Boolean(), nullable=False),
    sa.Column('is_disarmed', sa.Boolean(), nullable=False),
    sa.Column('discovered_by_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['floor_id'], ['map_floors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('map_drawings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('floor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_drawings_floor_id', 'map_floors', ['floor_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('map_markers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('floor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_markers_floor_id', 'map_floors', ['floor_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('map_objects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_open', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('floor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_objects_floor_id', 'map_floors', ['floor_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('map_objects', schema=None) as batch_op:
        batch_op.drop_constraint('fk_objects_floor_id', type_='foreignkey')
        batch_op.drop_column('floor_id')
        batch_op.drop_column('is_open')

    with op.batch_alter_table('map_markers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_markers_floor_id', type_='foreignkey')
        batch_op.drop_column('floor_id')

    with op.batch_alter_table('map_drawings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_drawings_floor_id', type_='foreignkey')
        batch_op.drop_column('floor_id')

    op.drop_table('map_traps')
    op.drop_table('map_floors')
    # ### end Alembic commands ###
