"""stage1_item_database_rarity_system

Revision ID: 252d5cf1d886
Revises: 4254238cce0d
Create Date: 2026-04-13 20:28:52.501039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '252d5cf1d886'
down_revision: Union[str, Sequence[str], None] = '4254238cce0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('icon', sa.Text(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_bonuses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('bonus_type', sa.String(length=40), nullable=False),
    sa.Column('stat_name', sa.String(length=20), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('is_conditional', sa.Boolean(), nullable=False),
    sa.Column('condition_description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_weapon_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('dice_count', sa.Integer(), nullable=False),
    sa.Column('dice_type', sa.Integer(), nullable=False),
    sa.Column('damage_type', sa.String(length=20), nullable=False),
    sa.Column('range', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id')
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('base_price_copper', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('tags', sa.Text(), nullable=False, server_default='[]'))
        batch_op.add_column(sa.Column('created_by_ai', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.create_foreign_key('fk_items_category_id', 'item_categories', ['category_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_constraint('fk_items_category_id', type_='foreignkey')
        batch_op.drop_column('created_by_ai')
        batch_op.drop_column('tags')
        batch_op.drop_column('base_price_copper')
        batch_op.drop_column('category_id')

    op.drop_table('item_weapon_stats')
    op.drop_table('item_bonuses')
    op.drop_table('item_categories')
    # ### end Alembic commands ###
