"""remove has_rerolled_hp from characters

Revision ID: 27244a3396dc
Revises: add_has_rerolled_hp
Create Date: 2026-04-24 10:20:11.971378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27244a3396dc'
down_revision: Union[str, Sequence[str], None] = 'add_has_rerolled_hp'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_characters')
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.alter_column('base_speed_cells',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('6'))
        batch_op.alter_column('movement_used_this_turn',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('rank',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'common'"))
        batch_op.drop_column('has_rerolled_hp')

    with op.batch_alter_table('item_weapon_stats', schema=None) as batch_op:
        batch_op.alter_column('hit_stat',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'strength'"))

    with op.batch_alter_table('race_rank_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_race_rank_configs_race_id'))
        batch_op.drop_index(batch_op.f('ix_race_rank_configs_rank'))
        batch_op.drop_index(batch_op.f('ix_race_rank_configs_unique_rank'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('race_rank_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_race_rank_configs_unique_rank'), ['race_id', 'rank', 'rank_plus'], unique=1)
        batch_op.create_index(batch_op.f('ix_race_rank_configs_rank'), ['rank'], unique=False)
        batch_op.create_index(batch_op.f('ix_race_rank_configs_race_id'), ['race_id'], unique=False)

    with op.batch_alter_table('item_weapon_stats', schema=None) as batch_op:
        batch_op.alter_column('hit_stat',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'strength'"))

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_rerolled_hp', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False))
        batch_op.alter_column('rank',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'common'"))
        batch_op.alter_column('movement_used_this_turn',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('base_speed_cells',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('6'))

    op.create_table('_alembic_tmp_characters',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.INTEGER(), nullable=False),
    sa.Column('player_token', sa.TEXT(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('is_npc', sa.BOOLEAN(), nullable=False),
    sa.Column('is_gm_controlled', sa.BOOLEAN(), nullable=False),
    sa.Column('armor_class', sa.INTEGER(), nullable=False),
    sa.Column('current_hp', sa.INTEGER(), nullable=False),
    sa.Column('max_hp', sa.INTEGER(), nullable=False),
    sa.Column('strength', sa.INTEGER(), nullable=False),
    sa.Column('dexterity', sa.INTEGER(), nullable=False),
    sa.Column('constitution', sa.INTEGER(), nullable=False),
    sa.Column('intelligence', sa.INTEGER(), nullable=False),
    sa.Column('wisdom', sa.INTEGER(), nullable=False),
    sa.Column('charisma', sa.INTEGER(), nullable=False),
    sa.Column('initiative_bonus', sa.INTEGER(), nullable=False),
    sa.Column('initiative_roll', sa.INTEGER(), nullable=True),
    sa.Column('initiative_order', sa.INTEGER(), nullable=True),
    sa.Column('attack_dice_count', sa.INTEGER(), nullable=False),
    sa.Column('attack_dice_type', sa.INTEGER(), nullable=False),
    sa.Column('map_x', sa.FLOAT(), nullable=True),
    sa.Column('map_y', sa.FLOAT(), nullable=True),
    sa.Column('token_color', sa.TEXT(), nullable=False),
    sa.Column('is_visible_on_map', sa.BOOLEAN(), nullable=False),
    sa.Column('status_effects', sa.TEXT(), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=False),
    sa.Column('is_alive', sa.BOOLEAN(), nullable=False),
    sa.Column('gold', sa.INTEGER(), nullable=False),
    sa.Column('turn_count', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('wealth_bronze', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('can_edit_own_items', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('race_id', sa.INTEGER(), nullable=True),
    sa.Column('level', sa.INTEGER(), server_default=sa.text("'1'"), nullable=False),
    sa.Column('experience', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('vision_radius', sa.INTEGER(), server_default=sa.text("'5'"), nullable=False),
    sa.Column('mana_current', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('mana_max', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('mana_regen_per_turn', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('place_at_table', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('show_hp_to_players', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('gm_notes', sa.TEXT(), server_default=sa.text("('')"), nullable=False),
    sa.Column('rank', sa.VARCHAR(length=20), server_default=sa.text("'common'"), nullable=False),
    sa.Column('age', sa.INTEGER(), nullable=True),
    sa.Column('gender', sa.TEXT(), nullable=True),
    sa.Column('max_inventory_slots', sa.INTEGER(), server_default=sa.text("'12'"), nullable=False),
    sa.Column('declined_stats', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('base_speed_cells', sa.INTEGER(), server_default=sa.text('6'), nullable=False),
    sa.Column('movement_used_this_turn', sa.FLOAT(), server_default=sa.text('0'), nullable=False),
    sa.Column('token_image_url', sa.TEXT(), nullable=True),
    sa.Column('spiritual_hp', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('spiritual_max_hp', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('has_rerolled_hp', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], name=op.f('fk_characters_race_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
