"""stage8_quest_system

Revision ID: 2c55803c7964
Revises: 378784d0fdd1
Create Date: 2026-04-14 10:22:20.541592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c55803c7964'
down_revision: Union[str, Sequence[str], None] = '378784d0fdd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quest_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source_npc_id', sa.Integer(), nullable=True),
    sa.Column('reward_gold_copper', sa.Integer(), nullable=False),
    sa.Column('reward_item_ids', sa.Text(), nullable=False),
    sa.Column('reward_description', sa.Text(), nullable=False),
    sa.Column('reward_is_hidden', sa.Boolean(), nullable=False),
    sa.Column('stages', sa.Text(), nullable=False),
    sa.Column('is_multi_stage', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_npc_id'], ['characters.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character_quests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('quest_template_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source_npc_name', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('current_stage', sa.Integer(), nullable=False),
    sa.Column('stages_completed', sa.Text(), nullable=False),
    sa.Column('reward_gold_copper', sa.Integer(), nullable=False),
    sa.Column('reward_item_ids', sa.Text(), nullable=False),
    sa.Column('reward_description', sa.Text(), nullable=False),
    sa.Column('reward_is_hidden', sa.Boolean(), nullable=False),
    sa.Column('reward_revealed', sa.Boolean(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quest_template_id'], ['quest_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character_quests')
    op.drop_table('quest_templates')
    # ### end Alembic commands ###
