"""kill_xp_reward

Revision ID: 350a344b0c1d
Revises: 0885481743df
Create Date: 2026-04-24 13:25:36.209651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '350a344b0c1d'
down_revision: Union[str, Sequence[str], None] = '0885481743df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kill_xp_reward', sa.Integer(), nullable=False, server_default=sa.text("'0'")))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_column('kill_xp_reward')

    # ### end Alembic commands ###
