"""stage4_status_effects_equipment_templates

Revision ID: 43fb2bc7cf58
Revises: 69c627818d70
Create Date: 2026-04-13 21:33:13.231272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43fb2bc7cf58'
down_revision: Union[str, Sequence[str], None] = '69c627818d70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('item_ids', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('status_effect_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=10), nullable=False),
    sa.Column('color', sa.String(length=10), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('effects', sa.Text(), nullable=False),
    sa.Column('default_duration', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character_status_effects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=10), nullable=False),
    sa.Column('color', sa.String(length=10), nullable=False),
    sa.Column('effects', sa.Text(), nullable=False),
    sa.Column('remaining_turns', sa.Integer(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=False),
    sa.Column('applied_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['applied_by_id'], ['characters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['status_effect_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character_status_effects')
    op.drop_table('status_effect_templates')
    op.drop_table('equipment_templates')
    # ### end Alembic commands ###
