"""bv2 map builder v2 tables

Revision ID: 4b807ffb72fe
Revises: 75be5262173a
Create Date: 2026-04-26 17:48:58.112140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b807ffb72fe'
down_revision: Union[str, Sequence[str], None] = '75be5262173a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bv2_library',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('snapshot_json', sa.Text(), nullable=False),
    sa.Column('preview_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bv2_maps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('cover_image_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bv2_locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('map_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('grid_type', sa.String(length=10), nullable=False),
    sa.Column('tile_size', sa.Integer(), nullable=False),
    sa.Column('cols', sa.Integer(), nullable=False),
    sa.Column('rows', sa.Integer(), nullable=False),
    sa.Column('background_color', sa.Text(), nullable=False),
    sa.Column('background_image_url', sa.Text(), nullable=True),
    sa.Column('ambient_light', sa.Float(), nullable=False),
    sa.Column('is_indoor', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['map_id'], ['bv2_maps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bv2_edges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('range_start', sa.Integer(), nullable=False),
    sa.Column('range_end', sa.Integer(), nullable=False),
    sa.Column('target_location_id', sa.Integer(), nullable=True),
    sa.Column('target_entry_col', sa.Integer(), nullable=False),
    sa.Column('target_entry_row', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['bv2_locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_location_id'], ['bv2_locations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bv2_entities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('col', sa.Integer(), nullable=False),
    sa.Column('row', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('props_json', sa.Text(), nullable=False),
    sa.Column('visible_to_players', sa.Boolean(), nullable=False),
    sa.Column('discovered_by_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['bv2_locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bv2_lights',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('col', sa.Integer(), nullable=False),
    sa.Column('row', sa.Integer(), nullable=False),
    sa.Column('radius_cells', sa.Float(), nullable=False),
    sa.Column('color_hex', sa.String(length=9), nullable=False),
    sa.Column('intensity', sa.Float(), nullable=False),
    sa.Column('source_kind', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['bv2_locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bv2_tiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('col', sa.Integer(), nullable=False),
    sa.Column('row', sa.Integer(), nullable=False),
    sa.Column('tile_type', sa.String(length=32), nullable=False),
    sa.Column('blocks_movement', sa.Boolean(), nullable=False),
    sa.Column('blocks_vision', sa.Boolean(), nullable=False),
    sa.Column('extra_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['bv2_locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id', 'col', 'row', name='uq_bv2_tile_cell')
    )
    op.create_table('bv2_visit_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('explored_tiles_json', sa.Text(), nullable=False),
    sa.Column('discovered_entity_ids_json', sa.Text(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['bv2_locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'location_id', name='uq_bv2_visit_char_loc')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bv2_visit_state')
    op.drop_table('bv2_tiles')
    op.drop_table('bv2_lights')
    op.drop_table('bv2_entities')
    op.drop_table('bv2_edges')
    op.drop_table('bv2_locations')
    op.drop_table('bv2_maps')
    op.drop_table('bv2_library')
    # ### end Alembic commands ###
