"""add trap damage dice count and type

Revision ID: 4ba69fbd39d9
Revises: 654fcf14ed7b
Create Date: 2026-04-30 15:31:46.601264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ba69fbd39d9'
down_revision: Union[str, Sequence[str], None] = '654fcf14ed7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bv2_traps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('damage_dice_count', sa.Integer(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('damage_dice_type', sa.Integer(), server_default='6', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bv2_traps', schema=None) as batch_op:
        batch_op.drop_column('damage_dice_type')
        batch_op.drop_column('damage_dice_count')

    # ### end Alembic commands ###
