"""stage6_races_classes_character_fields

Revision ID: 4ef14b36e2f0
Revises: 96e747247da2
Create Date: 2026-04-14 09:39:10.674652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ef14b36e2f0'
down_revision: Union[str, Sequence[str], None] = '96e747247da2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('bonuses', sa.Text(), nullable=False),
    sa.Column('special_abilities', sa.Text(), nullable=False),
    sa.Column('hit_die', sa.Integer(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('races',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('bonuses', sa.Text(), nullable=False),
    sa.Column('special_abilities', sa.Text(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('race_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('class_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('level', sa.Integer(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('experience', sa.Integer(), nullable=False, server_default='0'))
        batch_op.create_foreign_key('fk_characters_race_id', 'races', ['race_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_characters_class_id', 'classes', ['class_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('stat_modifiers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=20), nullable=False, server_default='manual'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stat_modifiers', schema=None) as batch_op:
        batch_op.drop_column('source')

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('experience')
        batch_op.drop_column('level')
        batch_op.drop_column('class_id')
        batch_op.drop_column('race_id')

    op.drop_table('races')
    op.drop_table('classes')
    # ### end Alembic commands ###
