"""add_attribute_points_available

Revision ID: 5c42b9b7aa6d
Revises: ae6deac58f2f
Create Date: 2026-04-24 13:13:21.626792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c42b9b7aa6d'
down_revision: Union[str, Sequence[str], None] = 'ae6deac58f2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attribute_points_available', sa.Integer(), nullable=False, server_default=sa.text("'0'")))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_column('attribute_points_available')

    # ### end Alembic commands ###
