"""add size_cells dot_template_id trigger_zone_size

Revision ID: 654fcf14ed7b
Revises: 924b67782e86
Create Date: 2026-04-30 12:32:18.285682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '654fcf14ed7b'
down_revision: Union[str, Sequence[str], None] = '924b67782e86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bv2_traps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dot_template_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_bv2_traps_dot_template', 'status_effect_templates', ['dot_template_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bv2_traps', schema=None) as batch_op:
        batch_op.drop_constraint('fk_bv2_traps_dot_template', type_='foreignkey')
        batch_op.drop_column('dot_template_id')

    # ### end Alembic commands ###
