"""mapdata_active_floor

Revision ID: 75be5262173a
Revises: 7c285a0821b3
Create Date: 2026-04-25 21:29:34.613980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75be5262173a'
down_revision: Union[str, Sequence[str], None] = '7c285a0821b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('map_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_floor_id', sa.Integer(), nullable=True))
        batch_op.alter_column('image_path',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('image_url',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.create_foreign_key('fk_mapdata_active_floor', 'map_floors', ['active_floor_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('map_data', schema=None) as batch_op:
        batch_op.drop_constraint('fk_mapdata_active_floor', type_='foreignkey')
        batch_op.alter_column('image_url',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('image_path',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('active_floor_id')

    # ### end Alembic commands ###
