"""phase6_addition_ability_builder_fields

Revision ID: 7758c240dd27
Revises: d4e5f6a7b8c9
Create Date: 2026-04-15 14:41:12.199317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7758c240dd27'
down_revision: Union[str, Sequence[str], None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('abilities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sa.Text(), nullable=False, server_default=sa.text("'\u26A1'")))
        batch_op.add_column(sa.Column('color', sa.Text(), nullable=False, server_default=sa.text("'#60a5fa'")))
        batch_op.add_column(sa.Column('flavor_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.Text(), nullable=False, server_default=sa.text("'[]'")))
        batch_op.add_column(sa.Column('ability_type', sa.String(length=20), nullable=False, server_default=sa.text("'active'")))
        batch_op.add_column(sa.Column('target_type', sa.String(length=20), nullable=False, server_default=sa.text("'single'")))
        batch_op.add_column(sa.Column('aoe_radius', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('damage_type', sa.String(length=20), nullable=False, server_default=sa.text("'physical'")))
        batch_op.add_column(sa.Column('custom_damage_type', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('hp_cost', sa.Integer(), nullable=False, server_default=sa.text("'0'")))
        batch_op.add_column(sa.Column('hit_stat', sa.String(length=20), nullable=False, server_default=sa.text("'strength'")))
        batch_op.add_column(sa.Column('damage_stat', sa.String(length=20), nullable=False, server_default=sa.text("'strength'")))
        batch_op.add_column(sa.Column('is_passive', sa.Boolean(), nullable=False, server_default=sa.text("'0'")))
        batch_op.add_column(sa.Column('passive_effect', sa.Text(), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('mana_cost',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('cooldown_turns',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('requires_hit_roll',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('effect',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'{}'"))

    with op.batch_alter_table('character_abilities', schema=None) as batch_op:
        batch_op.alter_column('is_unlocked',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'1'"))
        batch_op.alter_column('cooldown_remaining',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('character_memory', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_memory', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))

    with op.batch_alter_table('character_abilities', schema=None) as batch_op:
        batch_op.alter_column('cooldown_remaining',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('is_unlocked',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'1'"))

    with op.batch_alter_table('abilities', schema=None) as batch_op:
        batch_op.alter_column('effect',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'{}'"))
        batch_op.alter_column('requires_hit_roll',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('cooldown_turns',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('mana_cost',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.drop_column('passive_effect')
        batch_op.drop_column('is_passive')
        batch_op.drop_column('damage_stat')
        batch_op.drop_column('hit_stat')
        batch_op.drop_column('hp_cost')
        batch_op.drop_column('custom_damage_type')
        batch_op.drop_column('damage_type')
        batch_op.drop_column('aoe_radius')
        batch_op.drop_column('target_type')
        batch_op.drop_column('ability_type')
        batch_op.drop_column('tags')
        batch_op.drop_column('notes')
        batch_op.drop_column('flavor_text')
        batch_op.drop_column('color')
        batch_op.drop_column('icon')

    # ### end Alembic commands ###
