"""add_map_locked_for_players_to_sessions

Revision ID: 78dfd2bbf75f
Revises: 05fb7428ef76
Create Date: 2026-04-29 16:25:18.262483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78dfd2bbf75f'
down_revision: Union[str, Sequence[str], None] = '05fb7428ef76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('map_locked_for_players', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('map_locked_for_players')

    # ### end Alembic commands ###
