"""map_portals

Revision ID: 7c285a0821b3
Revises: c89bb9462cdf
Create Date: 2026-04-25 17:16:07.615447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c285a0821b3'
down_revision: Union[str, Sequence[str], None] = 'c89bb9462cdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('map_portals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('floor_id', sa.Integer(), nullable=True),
    sa.Column('col', sa.Integer(), nullable=False),
    sa.Column('row', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('target_map_id', sa.Integer(), nullable=True),
    sa.Column('target_floor_id', sa.Integer(), nullable=True),
    sa.Column('target_col', sa.Integer(), nullable=False),
    sa.Column('target_row', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['floor_id'], ['map_floors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_floor_id'], ['map_floors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_map_id'], ['map_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('map_portals')
    # ### end Alembic commands ###
