"""add bv2 character grid position fields

Revision ID: 865bbdab5232
Revises: b6e673e0638c
Create Date: 2026-04-26 19:34:54.873553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '865bbdab5232'
down_revision: Union[str, Sequence[str], None] = 'b6e673e0638c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_location_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('col', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('row', sa.Integer(), nullable=False, server_default='0'))
        batch_op.create_foreign_key('fk_characters_bv2_location', 'bv2_locations', ['current_location_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_constraint('fk_characters_bv2_location', type_='foreignkey')
        batch_op.drop_column('row')
        batch_op.drop_column('col')
        batch_op.drop_column('current_location_id')

    # ### end Alembic commands ###
