"""extend_bv2_traps_phase17_r5_v2

Revision ID: 924b67782e86
Revises: 78dfd2bbf75f
Create Date: 2026-04-29 20:52:32.286042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '924b67782e86'
down_revision: Union[str, Sequence[str], None] = '78dfd2bbf75f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bv2_traps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('undodgeable', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('attack_bonus', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('dot_effect_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('charges', sa.Integer(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('charges_used', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('is_armed', sa.Boolean(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bv2_traps', schema=None) as batch_op:
        batch_op.drop_column('is_armed')
        batch_op.drop_column('charges_used')
        batch_op.drop_column('charges')
        batch_op.drop_column('dot_effect_json')
        batch_op.drop_column('attack_bonus')
        batch_op.drop_column('undodgeable')

    # ### end Alembic commands ###
