"""ability_typed_configs

Revision ID: 9598e84453ca
Revises: ee1d2737fa51
Create Date: 2026-04-24 20:12:07.913066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9598e84453ca'
down_revision: Union[str, Sequence[str], None] = 'ee1d2737fa51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ability_level_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ability_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('target_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('aoe_radius', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('damage_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('custom_damage_type', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('mana_cost', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('hp_cost', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cooldown_turns', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('requires_hit_roll', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('hit_stat', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('damage_stat', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('damage_dice_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('damage_dice_type', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_passive', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('passive_effect', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('effect', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('range_cells', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_uses', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_conditional', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('conditional_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.drop_column('config_json')

    with op.batch_alter_table('ability_rank_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ability_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('target_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('aoe_radius', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('damage_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('custom_damage_type', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('mana_cost', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('hp_cost', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cooldown_turns', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('requires_hit_roll', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('hit_stat', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('damage_stat', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('damage_dice_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('damage_dice_type', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_passive', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('passive_effect', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('effect', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('range_cells', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_uses', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_conditional', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('conditional_text', sa.Text(), nullable=True))
        batch_op.drop_column('config_json')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ability_rank_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('config_json', sa.TEXT(), nullable=False))
        batch_op.drop_column('conditional_text')
        batch_op.drop_column('is_conditional')
        batch_op.drop_column('max_uses')
        batch_op.drop_column('range_cells')
        batch_op.drop_column('effect')
        batch_op.drop_column('passive_effect')
        batch_op.drop_column('is_passive')
        batch_op.drop_column('damage_dice_type')
        batch_op.drop_column('damage_dice_count')
        batch_op.drop_column('damage_stat')
        batch_op.drop_column('hit_stat')
        batch_op.drop_column('requires_hit_roll')
        batch_op.drop_column('cooldown_turns')
        batch_op.drop_column('hp_cost')
        batch_op.drop_column('mana_cost')
        batch_op.drop_column('custom_damage_type')
        batch_op.drop_column('damage_type')
        batch_op.drop_column('aoe_radius')
        batch_op.drop_column('target_type')
        batch_op.drop_column('ability_type')

    with op.batch_alter_table('ability_level_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('config_json', sa.TEXT(), nullable=False))
        batch_op.drop_column('notes')
        batch_op.drop_column('conditional_text')
        batch_op.drop_column('is_conditional')
        batch_op.drop_column('max_uses')
        batch_op.drop_column('range_cells')
        batch_op.drop_column('effect')
        batch_op.drop_column('passive_effect')
        batch_op.drop_column('is_passive')
        batch_op.drop_column('damage_dice_type')
        batch_op.drop_column('damage_dice_count')
        batch_op.drop_column('damage_stat')
        batch_op.drop_column('hit_stat')
        batch_op.drop_column('requires_hit_roll')
        batch_op.drop_column('cooldown_turns')
        batch_op.drop_column('hp_cost')
        batch_op.drop_column('mana_cost')
        batch_op.drop_column('custom_damage_type')
        batch_op.drop_column('damage_type')
        batch_op.drop_column('aoe_radius')
        batch_op.drop_column('target_type')
        batch_op.drop_column('ability_type')

    # ### end Alembic commands ###
