"""stage5_combat_events

Revision ID: 96e747247da2
Revises: 43fb2bc7cf58
Create Date: 2026-04-14 08:12:44.847012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96e747247da2'
down_revision: Union[str, Sequence[str], None] = '43fb2bc7cf58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('combat_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('current_participant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('combat_participants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('combat_event_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('initiative_roll', sa.Integer(), nullable=True),
    sa.Column('initiative_bonus', sa.Integer(), nullable=False),
    sa.Column('final_initiative', sa.Integer(), nullable=True),
    sa.Column('turn_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('show_hp_to_players', sa.Boolean(), nullable=False),
    sa.Column('show_ac_to_players', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['combat_event_id'], ['combat_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('combat_participants')
    op.drop_table('combat_events')
    # ### end Alembic commands ###
