"""add_mana_max_to_npc_templates

Revision ID: ae6deac58f2f
Revises: 27244a3396dc
Create Date: 2026-04-24 12:25:08.010633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae6deac58f2f'
down_revision: Union[str, Sequence[str], None] = '27244a3396dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('npc_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mana_max', sa.Integer(), nullable=True, server_default='0'))

    with op.batch_alter_table('race_rank_configs', schema=None) as batch_op:
        batch_op.alter_column('rank',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('race_rank_configs', schema=None) as batch_op:
        batch_op.alter_column('rank',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    with op.batch_alter_table('npc_templates', schema=None) as batch_op:
        batch_op.drop_column('mana_max')

    # ### end Alembic commands ###
