"""stage2_inventory_system

Revision ID: b3db128f567e
Revises: 252d5cf1d886
Create Date: 2026-04-13 20:46:55.813888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3db128f567e'
down_revision: Union[str, Sequence[str], None] = '252d5cf1d886'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gold_copper', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('can_edit_own_items', sa.Boolean(), nullable=False, server_default='0'))

    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equipped_slot', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('custom_notes', sa.Text(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('acquired_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.drop_column('acquired_at')
        batch_op.drop_column('custom_notes')
        batch_op.drop_column('equipped_slot')

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_column('can_edit_own_items')
        batch_op.drop_column('gold_copper')

    # ### end Alembic commands ###
