"""add sight_range_cells to characters

Revision ID: b6e673e0638c
Revises: 4b807ffb72fe
Create Date: 2026-04-26 18:47:41.207723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6e673e0638c'
down_revision: Union[str, Sequence[str], None] = '4b807ffb72fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sight_range_cells', sa.Integer(), nullable=False, server_default='8'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_column('sight_range_cells')

    # ### end Alembic commands ###
