"""map_templates_and_chests_v2

Revision ID: c89bb9462cdf
Revises: bfe0a0f05cd3
Create Date: 2026-04-25 15:57:14.133909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c89bb9462cdf'
down_revision: Union[str, Sequence[str], None] = 'bfe0a0f05cd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('map_library',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('map_data_json', sa.Text(), nullable=False),
    sa.Column('image_path', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('map_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('map_chests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('floor_id', sa.Integer(), nullable=True),
    sa.Column('col', sa.Integer(), nullable=False),
    sa.Column('row', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('items_json', sa.Text(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('visible_to_players', sa.Boolean(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('lock_dc', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['floor_id'], ['map_floors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ability_level_configs', schema=None) as batch_op:
        batch_op.alter_column('notes',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('map_floors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('map_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('image_path', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.Text(), nullable=True))
        batch_op.create_foreign_key('fk_map_floors_map_id', 'map_templates', ['map_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('map_floors', schema=None) as batch_op:
        batch_op.drop_constraint('fk_map_floors_map_id', type_='foreignkey')
        batch_op.drop_column('image_url')
        batch_op.drop_column('image_path')
        batch_op.drop_column('map_id')

    with op.batch_alter_table('ability_level_configs', schema=None) as batch_op:
        batch_op.alter_column('notes',
               existing_type=sa.TEXT(),
               nullable=True)

    op.drop_table('map_chests')
    op.drop_table('map_templates')
    op.drop_table('map_library')
    # ### end Alembic commands ###
