"""bv2_entity_detail_tables_and_drop_props_json

Revision ID: d928752f9387
Revises: 865bbdab5232
Create Date: 2026-04-26 21:16:55.935764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd928752f9387'
down_revision: Union[str, Sequence[str], None] = '865bbdab5232'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bv2_chests',
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('lock_dc', sa.Integer(), nullable=False),
    sa.Column('icon', sa.String(length=20), nullable=False),
    sa.Column('is_opened', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['bv2_entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_table('bv2_cover_zones',
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('cover_level', sa.String(length=20), nullable=False),
    sa.Column('material', sa.String(length=20), nullable=False),
    sa.Column('blocks_line_of_sight', sa.Boolean(), nullable=False),
    sa.Column('is_destructible', sa.Boolean(), nullable=False),
    sa.Column('current_hp', sa.Integer(), nullable=True),
    sa.Column('max_hp', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['bv2_entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_table('bv2_npc_spawns',
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('npc_template_id', sa.Integer(), nullable=False),
    sa.Column('auto_spawn_trigger', sa.String(length=20), nullable=False),
    sa.Column('spawn_count', sa.Integer(), nullable=False),
    sa.Column('has_spawned', sa.Boolean(), nullable=False),
    sa.Column('is_hostile', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['bv2_entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['npc_template_id'], ['npc_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_table('bv2_portals',
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('target_location_id', sa.Integer(), nullable=True),
    sa.Column('target_col', sa.Integer(), nullable=False),
    sa.Column('target_row', sa.Integer(), nullable=False),
    sa.Column('is_one_way', sa.Boolean(), nullable=False),
    sa.Column('requires_key_item_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['bv2_entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requires_key_item_id'], ['items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_location_id'], ['bv2_locations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_table('bv2_traps',
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('trap_type', sa.String(length=20), nullable=False),
    sa.Column('damage_dice', sa.String(length=20), nullable=False),
    sa.Column('damage_type', sa.String(length=20), nullable=False),
    sa.Column('dc_detect', sa.Integer(), nullable=False),
    sa.Column('dc_disarm', sa.Integer(), nullable=False),
    sa.Column('dc_save', sa.Integer(), nullable=False),
    sa.Column('save_ability', sa.String(length=10), nullable=False),
    sa.Column('is_triggered', sa.Boolean(), nullable=False),
    sa.Column('is_disarmed', sa.Boolean(), nullable=False),
    sa.Column('trigger_mode', sa.String(length=20), nullable=False),
    sa.Column('reset_on_trigger', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['bv2_entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_table('bv2_chest_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chest_entity_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chest_entity_id'], ['bv2_chests.entity_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bv2_cover_cells',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('zone_entity_id', sa.Integer(), nullable=False),
    sa.Column('col', sa.Integer(), nullable=False),
    sa.Column('row', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['zone_entity_id'], ['bv2_cover_zones.entity_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zone_entity_id', 'col', 'row', name='uq_bv2_cover_cell')
    )
    with op.batch_alter_table('bv2_entities', schema=None) as batch_op:
        batch_op.drop_column('props_json')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bv2_entities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('props_json', sa.TEXT(), nullable=False))

    op.drop_table('bv2_cover_cells')
    op.drop_table('bv2_chest_items')
    op.drop_table('bv2_traps')
    op.drop_table('bv2_portals')
    op.drop_table('bv2_npc_spawns')
    op.drop_table('bv2_cover_zones')
    op.drop_table('bv2_chests')
    # ### end Alembic commands ###
