"""stage11_combat_actions_weapon_fields

Revision ID: eb0ca4abdc8b
Revises: 62bbf1808bed
Create Date: 2026-04-15 08:09:21.922569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb0ca4abdc8b'
down_revision: Union[str, Sequence[str], None] = '62bbf1808bed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('combat_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('combat_event_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('attacker_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(length=20), nullable=False),
    sa.Column('weapon_id', sa.Integer(), nullable=True),
    sa.Column('attack_roll', sa.Text(), nullable=False),
    sa.Column('damage_roll', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attacker_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['combat_event_id'], ['combat_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['characters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['weapon_id'], ['items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('item_weapon_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weapon_range', sa.String(length=10), nullable=False, server_default='melee'))
        batch_op.add_column(sa.Column('weapon_properties', sa.Text(), nullable=False, server_default='[]'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_weapon_stats', schema=None) as batch_op:
        batch_op.drop_column('weapon_properties')
        batch_op.drop_column('weapon_range')

    op.drop_table('combat_actions')
    # ### end Alembic commands ###
