"""ability_levels_ranks_xp_config

Revision ID: ee1d2737fa51
Revises: 350a344b0c1d
Create Date: 2026-04-24 15:44:51.651858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee1d2737fa51'
down_revision: Union[str, Sequence[str], None] = '350a344b0c1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ability_level_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ability_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['ability_id'], ['abilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ability_id', 'level', name='uq_ability_level')
    )
    op.create_table('ability_rank_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ability_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.String(length=20), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['ability_id'], ['abilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ability_id', 'rank', name='uq_ability_rank')
    )
    with op.batch_alter_table('character_abilities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ability_level', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('ability_rank', sa.String(length=20), server_default='common', nullable=False))

    # Update existing rows to have default values (server_default only affects new rows)
    op.execute("UPDATE character_abilities SET ability_level = 0 WHERE ability_level IS NULL")
    op.execute("UPDATE character_abilities SET ability_rank = 'common' WHERE ability_rank IS NULL")

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('xp_threshold_config', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('xp_threshold_config')

    with op.batch_alter_table('character_abilities', schema=None) as batch_op:
        batch_op.drop_column('ability_rank')
        batch_op.drop_column('ability_level')

    op.drop_table('ability_rank_configs')
    op.drop_table('ability_level_configs')
    # ### end Alembic commands ###
