"""stage9_map_markers_drawings_fog

Revision ID: f1ef6d6d5b1e
Revises: 2c55803c7964
Create Date: 2026-04-14 10:45:06.267487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1ef6d6d5b1e'
down_revision: Union[str, Sequence[str], None] = '2c55803c7964'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('map_drawings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('map_id', sa.Integer(), nullable=False),
    sa.Column('drawing_type', sa.Text(), nullable=False),
    sa.Column('points', sa.Text(), nullable=False),
    sa.Column('color', sa.Text(), nullable=False),
    sa.Column('line_width', sa.Integer(), nullable=False),
    sa.Column('fill_opacity', sa.Float(), nullable=False),
    sa.Column('visible_to_players', sa.Boolean(), nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['map_id'], ['map_data.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('map_markers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('map_id', sa.Integer(), nullable=False),
    sa.Column('marker_type', sa.Text(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon', sa.Text(), nullable=False),
    sa.Column('color', sa.Text(), nullable=False),
    sa.Column('visible_to_players', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['characters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['map_id'], ['map_data.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vision_radius', sa.Integer(), nullable=False, server_default='5'))

    with op.batch_alter_table('map_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remember_explored', sa.Boolean(), nullable=False, server_default='1'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('map_data', schema=None) as batch_op:
        batch_op.drop_column('remember_explored')

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_column('vision_radius')

    op.drop_table('map_markers')
    op.drop_table('map_drawings')
    # ### end Alembic commands ###
